# Video Generation Settings
video:
  fps: 30
  resolution: [1920, 1080]
  default_duration: 5  # seconds per slide
  transition_duration: 1  # seconds
  background_color: [255, 255, 255]
  text_color: [0, 0, 0]
  
# Text-to-Speech Settings
tts:
  default_language: "ar"  # Arabic
  supported_languages:
    - ar  # Arabic
    - en  # English
  voice_rate: 1.0  # Speed multiplier
  
# PDF Processing
pdf:
  max_chars_per_slide: 300
  extract_images: true
  
# Audio Settings
audio:
  format: "mp3"
  bitrate: "192k"
  
# Output Settings
output:
  video_format: "mp4"
  video_codec: "libx264"
  audio_codec: "aac"
  quality: "high"  # high, medium, low
  
# Template Settings
templates:
  default_template: "professional"
  font_family: "Arial"
  font_size: 48
  title_font_size: 72
  
# Processing
processing:
  use_gpu: false
  max_workers: 4

# PowerPoint Generation
presentation:
  theme: "professional"
  title_font_size: 44
  content_font_size: 18
  background_color: [255, 255, 255]
  title_color: [0, 51, 102]
  content_color: [0, 0, 0]
  
# Report Generation
report:
  page_size: "A4"
  title_font_size: 24
  heading_font_size: 16
  content_font_size: 11
  title_color: [0, 51, 102]
  margins:
    top: 1.0
    bottom: 1.0
    left: 1.0
    right: 1.0
    
# Excel Generation
excel:
  title_font_size: 16
  header_font_size: 12
  content_font_size: 11
  title_color: "003366"
  header_color: "CCDDEE"
  auto_width: true
